version: "3.8"

services:
  backend:
    build: ./backend
    container_name: resume_backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}  # Uses .env in backend folder
      PORT: 5000

  frontend:
    build: ./frontend
    container_name: resume_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
