version: "3.8"

services:
  backend:
    image: modinipadmasree/resume-builder-backend:latest
    container_name: resume_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}  # Uses .env in backend folder
      PORT: 5000

  frontend:
    image: modinipadmasree/resume-builder-frontend:latest
    container_name: resume_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
